---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-config-file
  namespace: external-dns
spec:
  encryptedData:
    azure.json: AgBEl4VM950o2l2hz53/QDSd8orRZzkc44QvlZ5r3dEgTI49HQly+Kyg49RWuOkfJSNrs8k0oaTqXkqrPRcPu9lVlBEiEGk4TD5G7xogjC1EoR7uLjPMxjzmMuJIVNZVHmT91mUmogv9iHJp43/+bdrRl7jqxlZeHyYhfsHm6k7/+9tkv4AuNqxXKsYcFHikNWR8R1tmFSU/3ZaG7xFSVyOJJ0ujhAvVw3wAOqpHLjI8N3ljH8qAGKuJAE2PuTTEIU68YPfVqVsd16Ttw3yVNUI52ZPhXUOgUZqReDbMEIUYnJ/scyyXIceFm+IgelzfMglE6sy/QRWzESv2aMITbuhHomFKs2hk0VcQOfTGytcgXNeqg+ickGXpvzXb+Y/VTfSMsjzeptm7NWzXS0yjGjRn7geVxYV6A9EtLEj1mNSFAMRE4DZpetvEi4gpY489M5MoZdMfznIxrle0xXk3DoKB0je4ykWkMEG+sfup/GNPIsFVJTI+RTiXAU7ihWBDGS13I/ijO6TLRxqqRbv/XsL1fW6fx4Zbs6iS8CLQ+GLUGUOkyyfYx47WCD3KqP6uY1mUAnVEXtLxVt96SjuoN8+f/PgVN8atsR/fVOQEj3vK91zxAR/doV3Y8hN3jcDrtLKPp9h2AuX8obvs0ZT1BfdGLKhMEoVZ8ypFDPOdTIyrIiTJd3JtraqDkN875nZSFfbdxxYllqYIqhpgVjXu3ub1pyizNOlZW7oY5ppEl/pa4TtVgbaqGXCklIuUMx7Af9pklqJ6haNxZFCZIIZfr/qPO4YvbVea/ogNsAVrAgo74K9odQReF/KhKhIXdWD+C1qExuKb+LwJwkaalxy/onZMi5jHSXKFvoQ9IrTSeZQFN3a/a7x8c6PKn7O5j18R+GAwM++bBfXOuLr9eqBuvjUD5yT/pPMLpGGQZJLMowvJxPXlNj98+M78iGuXK0eIIahrZIPiITVumNrNsPRJDoK6oRz8qpaCQKCYPul8UHEfz2t4vWdC0eo2ViEDzB856mq7zK63B1DooCotAL085iLu3mO5vHgAo1k=
  template:
    metadata:
      creationTimestamp: null
      name: azure-config-file
      namespace: external-dns
