---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.azure.clientID: AgAYv3Ewam2rd4eECd43NR8jA9Oasl/c9suhknlVKTfGUaLbzH2imqipp18IlLOVOUIURkPgbIpxKAhuUE5VWS3DWq0aMpXEZKCtNVqRQ2P93kUTvbs5f4JI6XXn6ZAtv/SNR3GYsrgqxwWs/KJIBrc7f8aJ5b+qy7HHa9GBqM6wum0jjbIHII6IVE06XpOEFwsgUQw8eaYoyJwk0I4uddWS+Xgq1g5LrrbDZW1YLnqNUbziFjW/DwPuL8i96rJS6WqOGztqtmMdc00fHNTvKor1AhhVwyUqZK7dnFl9Eg+XhIsKtZMrjt8vILZ3lp56PcJtXaMtsFJNkHrA1k6w7XOE9ysG62wLvFODMLgAv3nhsSISimaDFHQniA7dalCEP22xzoY31LidVQBQd++3sUxAkGCDwRaDWREuhjbeIcJtCh/2hzJIBixLYKuyzbiWNr8uL9IMUa108u/FRBcZDsdVHDIi0fllE3QIwr2R2Eo32ZtzV7+Cto/vEZ2PB/bt12Z4OZOspio/bbXChpgOjiUdnFSrXDFAQAQPhW8nY5EeiFobIkawWOm1UsC7+hs5aZRyuulqRT3V21c6ytbRBUmg6HunDP82DMSBQU+nYLI4+1NPhS67iKw6GySadvLT8KJuNnFmfz9HMg7zrRCv5PCANGpJvYCU2c5iZmQeXxT3FIOEO88LmE0qPVHLBtmtTxl3BwO23h8aG73J7epA85X7RhWWpnjx+34DKnZVaUJ6uQ/SM5s=
    oidc.azure.clientSecret: AgCverr+MTyhirWpX/GrxD13PXiiyPGdjvwQlLotnRyH7HzswcVrWEApo/7Y/Ce1xpQvjpau5o/PE4H8cxS5oPx91gF7cPzeswdCMb0jKjYU+JCTDXpH51WYFgtmFZ05XBsDzayK8eGGBGLe5d59IVo0ITA5iyGkMj3rQ+7WN3/QHsTZ4NEWjR1KaEGv7s+79NGD7wozn17XB0xeGp7Ukupv0qc9b1RCRK7Y0OS9ZglMfXr69NaOjRou/Tq48kNQMPoDa1RzIMGWP+Kh3T7ueWGcJ/Yj0nzqlwCfKUQ1hpdy7JP6BMMlsAmVqpYNJFho7KTRKyLK1lzj9XFulxsO9OcW3GH+DKu+6uVgfhJ1aVrCTcnIw/LZZr1D+5sHKO8NUYup+F1+H37FVwTwuRPdV3/QtMjqi6dltoXCVpRzkFrL/kRF6VeLVlGeMEayF8Z2lZlhWn1rdB1g3WBhNNqAx/2qJ9mNAIMpbvnP7ozZS4OPx5PirghlhhB3FWzP4U7SLGK7jesDJAXRvPINgy3/Ol1HWSzwfEFOZQqJEB02JlOnXfweR9ab52qh/rRi+Lkzjeew2Fhs8gJDmNy3eFneAszm61FTPteUvRXsCLhyu8PQqkA9JqgD/m0veo0M4yqS2JEl2DBR50C/a77HenhDW4MGB0YQGl7LXtgxbynuKIChfeQoZ6hDrsrv2wM5qkNaLexIZeBJIlQc6XHcdnL8XWrYn1n/mSqGHRuIyetEsdc2d0yGQVMFzmFN
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
