---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.azure.clientID: AgA9WId9SDiKzU59TsBzpnkVo5fliEiHQaOw9jGhyaeaFYXjkLI1yT/B2trZJkU7uO5ICVDqGoA+QQKeyLVaBEx08GvUBrNz9JiXwcge95McmeqDOLilZ9sO4Dz0oY7yH9ErmUmsNs5XIH9SPhvDVGAy1bzUB392v34utFO4ezlDdKq+1HxDnQ0R1h8MhasTZPUQDKKkdnwBxAxLrArSNyFO+txjreSKbj+z/3RsbAi+ID+tqLORY3srVDru2RDqAodM4ndTO9UB4LnlFgW3PZHQO+0Z5IXuCHKMj4z135KgF6XRL+YfT/2KtrwFsja/xD+O2xOMoKRI3y4m+Emz133vTDOPnp7gfaakqImq1KpRoWDEc8DTNKLLc3Yh3x7TSYohYzgJiRCs0gPspUJeKw1hIvmISyxyE+fqjJBHe7bX0ZLfYre2i0M6Yxrk+am1Fs0q2Ww/6OXWzGHzN8oU2j2KAb+McvGyuv+ADgUnXXylsG5+ajfTISXiGJZ5BhOS4UbZTGF0HDZe0IaAkHd5LqWpw9eksoVoLzG44Ewuco3eFBdXIj2qJHpgkREhLzQPraq50ivLl49ObEPS+8UOi4LKc0DVEOu3qFBgN8skg9+3ZIAWOq9OU4ccJKKIhKMqBC53FIBGWOQ4aCcbRgR+Kvdo31+8Fc5/qAtHU5x0mSjbbnSSmvMzIw02Xx36W610pHw2DTdo0RwQlRIrT073lew07tgOddKp+SutM6oqeNX3vLJnMIc=
    oidc.azure.clientSecret: AgBGrFt8YtzqnDyfOO9Xo+X5jMRc2d446VDwPPsCrgQzr1TRr7RbSRhg660gf0Z2d19tcJGwT779kvXj3d+DzLZ/5aXwzE6qDG8xG05HYht0kA/knxkiNiPmyTco0Bf0/d/BCAcmHKXN253g3lZgMLQW44OG10owesaJhhchxZ4blqzhO7fX5ME9aDFuPZOelqmqGrJmS5PRJ8kYGkQLDdNHThXqa0nfZgH1NS86Sc9Zc8LdX/SwiXeaSDkrvElQ3JDtWLYcVULb0jDkOCsj2f7T7qcyJFCwhA8LmCyYD149UDmk2lXQEuEUBlhufLb4epVHIfRF5sNi/N2cnZv+KxGivhJkH6YLImejvycoYtpDdx96Mg4m7p0iXrTbEz4s8aCQ4g6PMQ6/3iAZzYTzvfSZDpkA94ZwBXfSRqpInA15JQOGr5h3yMIrxIlWC73NqGsHuXXRAPynxhqVy2ilGwSyZSTgGiY/sRYdm/YsXfoysLzMWo1E9PayNC12csPmeagi0sthTo/kBJDcI/KQzpbHUz8ohVr9kFNTfSf79UrKJCgkQtm9EbSiJSRSqmjfmkbj6HaKDlz98kr+3CTGIoPpk5wSWqY+sPBLetPXay1iNFZ/mIJ1gA8ogf+W7oWwvhiJvErASViv9vzR+5ISxpE+kNDH+2li6M1UdwfDoDyV6VwqcOtHThwXZpwq3QrUXwUQu2ixduwU/48BW8F8YMAaCCeAbQg7SmNRlYMGjqBJatWCMpvTCXTS
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
