---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgBvVxq4paIX2Irz30Z+UBC8DxVH/fooVO6Y+ZmsX2WaNvP+zqSzQG7g18YXMeKDEXBFNIaKeG6tJQX0LFMxEeTZuhhhKo+Y6RWTvMhQQE4oYxW94mHGEZmp53m0QpTEtyliQ1oiROyE2eAbd46JQnbZDigHOATI3JTAD8nyy8hfszhTFWdvVVPj4BHGaA50r3I051ymLmxZY8g1rJXFbOE8X+1Kr4poDR592ie4Ag2aMTJF/qOuXhoa+AzHJxul47rUBmDgEHIQXPaj5dOD6C19n+CLrwYhdRqpfgnl9261oYLIB94lYFiKavX3kVuCZCDhy6rz8rX1wMEnoY1P8dNe+BqvZatepLfBHxv1eYlOiO3+55GFbjOBLJ3hmlFnab+EMwXUkwl+9ltq2+mu+RiwaxDCO0nJ9UOXEHEBUrdaCy8V5i5vaNQWc3Ys8CP+KbiunNtdrsU8koRvBPPr3c4Pk06cD9UnOHnM1sFvwq7ETdlrvYDDwqZFFqSpOecwMhBgU36pTAjCUL3wTjPiJG5c93ItiioEn6bmnMFid4C6jHPwiLuoHxnGR7g6b5z6Za/jtXDTc1Vvpm+HZ1cZHLl3gaTZBw7aV+xcvPK7CkRqlapzqdDN+6XJkBgkpuhZNY1/Ku42FlclALH5RbnESHiEKuEaEHp5JXXzoaoUoXojUkuvj8s3T1G9P2butQzor/6BdIAateJuDT07e6iO2fMJWik0jpAKEZncHXEMOGpevgII/yjKUtOx
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
