---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgB0cS2vwG3YdEaJGkN07Q/Ncg8gqX37Lt/O+1skHFCeYbFQE00mv6uo3kdfGw7gsZ2qnocgPdkaZntvG/rs4v2g3OQ8ilRyuGWion6c7yax0Ofx/7AzoukLsSgdyR7BKEGVoWvnQwONVmWYDDf5z92nqTP65WDWm4kkNJzGA7O+GelBxvw72haVS3uXkQCEijtbGxkWQKLAo4hkwlJWGAtGnL/0NX2R+B5k/0yKVPuz9v/sKIRUmRFQnuYvI0qn+ksGiCeO1U3c8jdvplby9R03eNpob8ZMv9vxN4ChC3czNlR6pEjWymDGogCGEEsWtvwZ2APDEvEljdX09YNivVzhcZ4d8YJWPLf2ldAhpgvOyV7IecuhaPpcQhoS2jmYjvM9KJXWEaFh3VXBgr8SFo/Amvi0nT4pW7El4ICgYJnVw5cCmnjWCR7Oialr+EryxePOnFVpUPQLotfNCUqiM5sCgrLBjFRv7ULUhp1H+w5W8CSXikFFrRJ4st8juql8hbQE7iGimxU9Bks6bXP342rxTtwmYrKaDF1Rzh8hy8dtWJ7tlovCt/3qfA82p+du2mjVWrL90TSZ866Kb4PXHMd0vs9E2Z5w+5KeEeXmJjhQgRNTciI0MYjw8ZIf1q1eHvtVlUhRHcGKNFvo/lEqTN0U7QP10AOVWsIWSPWyDUHJwAPCP9PoXcfrpYvyMmDsCp/mqf7+YHlKIlB6S8EPeMR0C8/KYXo1PsfRsw/2sMDW6H/XoF79pFIx
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
