---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgBoYDarMF9vEVtObK49YzchTWWyygUP99ODB+M6FlpdrZeVubVZaujDaGhF7TA14ozvpjWIEJFE+bCsiOFbHgqKXpGdlHSxvcjow5vLQ8SKKf/Bbu80Lx0bRtP9oSfcNN5SuahSKFt2zgyf2dK8bobePDAX3icDpGtLVxf/WKt82mSCv0oWVLyYhvDMn8QEq5FJiJVw8hBMgcRW8JIFWk55O+ynHNKEwYw2+9Y9gXHQsxtIAHn8Dd/QvRLpN40CuU2k7h8lbkEFNjr6UQzhuMuWDggtt2MlMI26XfzKlw1bhMoFJf0eHpUVfHspKNEkpyCKeIUbcUpYpJ/KqCaUk4xomyMuJpXJN+A8pN7CCaNz/F02JAZDUeOAsXpln+J25eC3KeveLVwJtCNrsapJ1xjpX1Il1Ja9uSnTScPDgpGO+asbAt/8fI5CnaMY+EdMJ3RUiDV3Kz2/EuyR296XbR4Kl7CMaJ6eD8QtQniBSi83jArDYcDG0PpccBdJjjs5GdOWWCRsz6iJgXfsqjC1lPeh42tgmXNKwT3QdQ4pDI/8zX5V/AMPA0uAI6h6FAAq6k6vhO0r3NmuAmnzACS8fFQbP7IVW6M8/B2Pu6ymJ80jM5o9lrsu1pyooVFDjSKt21jA5iFey1kXt/ZmMaB/0diAfP8UaHQaeLzMG9mEchiRT17PB3RN9wtbiDRMDt2Gs8njD8tm4Um4XfQpcE5ANvqeUpywq++Y2ZCiRXGCcCu0vUhrqhMS/PiB
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
