---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgCTR1tKcH+tDNPXW1LTOz/DHxxtnC5sNNm27RKJWLAsZJEiYKeBZjuVayEF4Umb4hqJKfWT7rsONFX5TB5z2pVHM05yGj3cgtvq8/sSJnTikMoedkKTuJbjzRuX5dFUwaJuZhHJdUEhZ/zcR4m6N4X5D2ZNNWtVnjz1A2QqVx6Rvx8n4OCOqPynmWACEv5zP36FgoTRD7GKuzph3FjK+CuFZ4IS4QTKdbgeR6q2W++tVSoncpVH2SCa0MA5BcFUtsWnnQS/q6kRWa34l9Tcfb8Kp9ONfl+cSeMEbZfOb4xD3yXLGMY+2+HdwBpU2jG6DkdUIvgV4MU1mry4hoNhtRtU+YPvTDHIrLgsQGquRSqnSzJx5i1245wKXt3cHTQphagrOunG2gejfAL3uso9MRSR/nARO+z3Kyws8mEwyMq/1Gm3hTUaSo1X/oR4R1HiqHQWOaI1QZzWDLrdIBX5PwN8q6mTyDsEk6Kc63OYE1yYAThDNITlbCuB8kVSE2wLDHsQGvJ7lGjyqXj3INdvXscraoxbUugmhyKcPp4TJPKmctXdVKSepb1HAkOSMmgieuqR8YK12F6olUysMxB45w1i9aOrnBmji5/AZ7ocobSFASPKHZq7NEyHzXXHGon4XCvBg/AWVWK4oR4LljkuHtO0/NGbG6ZjFPczmHnYDFfJO52baqIzo9Eo5Sfw9F9nH48UCbrXhzyJZFFLKJh2vENdQV4aefpvhrDvBxkxymk7gashiK1BfbX4
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
