---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgCOPpuGGKmXaWZyM4M+CwcJCod3itcq5mrAWbqr71eEi7FdL8OaErsB1Nhvo0/IrftclGrJiVaZIsu4/cwSOq+iTCrYXjqZQN2TYEnyM4mZ6kCiKxMvK9Um68V8co/90FLYEzIeO3ImhhyJKExaEwii6CLj3TEPx5O7UoVgr5zRFmZbubRkaNRyGsK9hEQWW4U5uswoaquo/FTzygK1WPuAZiNBmKejQfO0nJ62v//Ok+jftHPcoSDLLECL2VXNlCISKlNW9+/wQTEHu2JqDEXGgDuW+czpy+GKja6NhPl76FzvhvJPaO7ecx+jVJdgL+XrmS2FKGvjM4i9AL6kNIG2nceMwrgp12PB4VN5ofRy8cgdOE1rOAXxChwnUzN0lGRvcw8470YDkUccSWCja85Q216Vw046u2nVvbKeDiXvThVKg+apHyxYMmpj+ciqr3NmPxavTADnfjvoVD+BTVM2PI66YCucPjUM0SNZLK/qo2B9jqVPMyL8zEcEV8C2ESBQmWAFcDuws2lOgkWh6z5yaZjxlMDjoKW1lXVoDjA9v7gCeiP96K2bbur6pvAWYoU58cDLo90AlSeWpTc2ALtGoZ0gciy37CD8KhTgrHiW9t8OwfAFMngareDjyxyBFA+YjCLiFEpZ17LT89XIk/8ji6FR0jd13rVVwAEiBKBMIGkO6UUedy8GqCn16mkT7t8uB39uzfUhUjFwBJZIdbysRUZ+lMnSh1IsPsw8GkSaXr+gTB2b+hQ/
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
