---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgBl2p4yh+jP7xN/GjktScJ5OeKe2gQV57wLBqQELHucLzzU86YHAORl8psTligJ1M3TavnCUZhT7sjiWALJaeEEXUtbsc5UBOrHp0Iu9mTV3sCob7WltfFwUSPHPTnPcVIWnrVjq7Tw8yhusJz45NSuf7/qVRykv29kegohGUiL6nd7jTWrQWjYdSYVQBGo6Nai3EvbajfHUUVaTTfTaq9l35siwIA7HrqTIbOEIuImoTdjSZQ9pr5Ktcm0RTvmgA9CBiKAEcgCOcBoCv/1WRQs8I+u5D4CLcZWt57JidMQSr9FS22dl1nemxkoSe4iPeVJfrqk8s3fZptQrm67d3GZzp47SdcYg+gZsFTKRQvVMafjYXOUxXfN5JNo0gZeor6UGzbUr1cu9nr4C4vjvLpMotV+B8oyVhKBMKw8HDeK4CR/7g/GrgziX2W+j54ispEEgnVR8gD+aKbgG0cyC3nwFTKOr1HgvL8mrwjL1S2ikRKeamN9QIThcXSoT+VJlQNXC62PPN+0z1BaE3fyM8uds/YVG2a4VjRI/4M6yUIA5FTxozwtaDmulMZqHoRxA4v8nHcrkjAvFtocdSQI5QtIoo04RzLkIf5J0Fodf6h1fVi1UvB358TzYuphYh1wUo7y0xNewKNZ4tX3omGohH7q/5p1E/g7yH95Jfe99yVc/jhgQcCAMM+iyaxSSvSH93v8DRxpUMFce3V6Hc7RiZJ31X2C9Qe/zxbEIp4IBwBtuBRsRZDeYjHU
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
