---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgAs03uipQOntvhTzyAhWr4cWiJYYIsmet0WRU77yEAtX9jPEWr84BVB3VxA+uY0PdH5hs3CSJmtwdqTI0EHBMpZFolpRHJYVSoeVrQP1I+vGoDi1hssB2ECNu5YO38b3kFBCkuBTpsgiAiNj/CaV/M6hieQLeZ+QqqzeoiS9hHS6oEDFe7fOm+7HOU+rhEID2IthwyT5G7KC4A4/JT4NCyOfPW3Y3bBKcLmxlIMp7firhxaKO0kym43+nZAYWXmQJKK9Yfv23Q6gS0EfmWnWKMiluQzlcjyrdlAa5HL/BzROeRTRPGMecY4duEwkqHOcS8PCzytckFsHVj/WtmrL/gbg3YNBU27aqwV1bUyKz8DGGHWOTbp7Gz53uXT5V11HXMvjNpGu1QUOuYYGxbCwbbcIN6I6qOHf6CjE2ljMbrwWaaDGd4EMwf0FCKigssgBFVKREwHNEEoDOqDnLPxroI5Tl2sccOaH66p8CrsYKEQZ51gDkGzOOoNaChph0xEp9eY/F1T7CPc5CSUkzcqMQKnJ9FRw5Qdh2vR4uCPENVAnDYXfVHHInm1Kxl0v851cn1xqRe1OYFe4/Wa0NecZUQDs819vMs0XcdPcINxcLO07xFqVxQrDBnWTsQQ+z1+9lgeYzjitKG9dMANbJ6Ibu9bdMQ7MMHHoay3dOPLtLOK2w/+Gv/cfyNZLGlt8nayQ6UoZFe09cDhcdF/ML0p4p2nKyZJNkUU8FjUJTHh+N5LTVMJeBo6rn4N
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
