---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgAHzbaW1Hh+BeXjRKsALLWK1uxX3bRuhMdJA6xW9XU/Gl2smyhnkVx8nAyun9KK8afO/P+LG+YvhsRfIyiHW9PURrIrU/RTLdCKXe+cl59iLJImkcXrH++oBbHfVVqbHHqeq+fLXKhShqpCl9YhefoDDFJzlTXt1KKSbHg9U8o/zabLRjqqA9erujXi52BO1vVP1OYJsl7H0nhj4BQf+OIlCDw89YCNjrC7wcef47H4EtOyMBUu82lbUdqx2k3BSmNYKkbTgcUfWn6AYxWtjhXmjhqq5qYxVozQo9uv6B4wf0TW1LOgve13tGee0N4lr8ynKtCtxORdsnEzs8P3MOMw9TEsb/I7V9HSFEbIFDSDuHRHzQafIm/iyUuwtqp2hRt45aNrAlsaACfup8nNDvPgspsuvkfDZjX99QFmZnRo0PNV+WXG4ZvDbLsOiaxUJlIZvUjphpMFxh1arlMh/M62QZfwwaE5Ougzy3ov0V8WxJhGNkUY1Dk90KqfcHBjMw3q6qnR6S9vG/ih+ry2Hrj4Mj6qfyrRRdOSnXa387PKbjwoOQomH7tgA3j0MZ0pKCL0SQjaN5P6Pm6z2OQvQmJpNUNt6AsQtirjuOX1gD1MQv/Vx7cR5uFUXASqdCHNon1KXD3u1t+M8RDR2BUNOilKFQuxU+aco383yke6X8iV4U7eiTE8Bh6E7tkPhFzkqvHZccAiv1HwumHGtFTaGclkn1bZs2bLMx1rU6bqgmFLH+DfpSZ5SjLn
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
