apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: komoplane-route
spec:
  parentRefs:
    - name: pod-gateway
      sectionName: https-listener
      kind: Gateway
      namespace: projectcontour
  hostnames:
    - "crossplane.pod.nvtc.io"
  rules:
    - backendRefs:
        - name: komoplane
          port: 8090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: komoplane-http-redirect-route
spec:
  parentRefs:
    - name: pod-gateway
      sectionName: http-listener
      kind: Gateway
      namespace: projectcontour
  hostnames:
    - "crossplane.pod.nvtc.io"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
