---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAX6jEqXb0bJNErO9FD9g59CQa4+vzB0Eo7hDHuCbmFUJWnvOWlY4n7roSzMc1MQrwHIYRwAtXOCIyRZEav8gODxJtg7NhOvpGmbb3vff+HcCUzEqW0nf3xtvB6Knu4WdJIcL6VeWX5PFKh2vY59YdbsWi1o75d/IbDDdT5Rc6mv8Z3efdPxkc7fGoxlIc8kOYrkqGq+ElF457EQeaJMWUCtZ0bkY9KmG/jIfNhA7q6nZunZVhHrxqqRobpHuwDCKW9vWmUE+HMDKq/wbwGJd24DgZP8AvWvUHsLF1KY5/P70PvWR3xPhuRIUpXOWFpSc8egnrOOCcD2fsgcv3kQRMhqGmiYInLx9HO61t6xmX3XdrycRdQWE4+Z6KXTsaXncTkNMh0YGBSS6bMKkPcXOOUESmR80Bxa2q/vSU2ec0NdNsq1OQGWvLkrX2OkzSEG/F5h31H7pjFmB4xj2nui2Yze1O19P9Muat96W/DpDvWVvkeAVnuWHC6S4sbMJpE5Hcf6YdhVpWqX8doDMU7UqclUmq0/UWn/uTC2LZyOJCqDfQJPrd8FxV8U0TVBcXMKeBbK/WUM9XM7Y0RLGAHZjx0Kt6+15xaqhT6osGAwMbVDOGRw2FAkC10roGwPVIhSpNVVHNOxkyu6Tlxm2UJV6lAoY7ABviQAw1voD88aWPE+FY0xDTgJuo1TUg4eK9w0R3g1wtlJ5aWe4rI9T5Ss/vJMqYJuBmLmESP1At36ZzU/uelQF/2KV1sJn/wTGuoOfvZtPSR4mO13YaRqT/cgaQdR5AWJS5uejJZJ8CdPg6EYYXs8PAWO/cGuetbGdg7R81mfg9rB1y9y8hDyIhsGFIP0BEFVAVGRNcA1sqcWxrLptEEEvK/LopbRCdGTAXY7UBJHa9RJhpLQf6fr4WuGOzY4en4Pm7356uuyKpS3pTOdUIlJssEjV6po/a2F0zHY8ic/GW9OrsZ6DvHtkpeoznfcLOegWv8Q7kkuKD1IXigd4KZZpr2boOjaM/lt5tnEIwjLcnPB5KMdZKyLLG7mx2ONfIj8ecSB7NwG/DyKDzbdC9hoo03EfUVO9Fku05zZUMsKNMavtsGSOhAs/DAvOWKQDFmtdHGPvqiVwJu/khHGhT0EYsvZpFteHGBOKg/N3UH6rkBjKR5rppLocBvIw5tZ99t4IOM2cTzwIZmEkahQ5E68RrnepnbJ9TWo0qCFULGpFlDAz5ngYh4dOK4oFdnYvdx2G5opPBiVuaO5ExTnscCDngYpljENM//b5R9h82ayQ7ppBFumIrEvVJaF3Vdp300BeE8gk5DMzIKX5OlPnLBoeK2vBnbQZYh2hsy2ZzyTScMjaGJhmKm5caUic9u7D7rPAWNTH/oHxwuGw8yLOwr/9mo2Anjo5PBlwG7wNJvX7tfGXKXeIUYplDbAmhzgL6tQHc5mcuPiRyRoLqkHP/TsgLgMuvQyX28CXEhvwlgR2t3uYzn6Uh/qUKgH48tnwz6ZH5wUCy1NruKLeP/3o7zbyScDQD99KoHxKcn5pqLv6Ov
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
