---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCuXpbvx/qv/V8wRhmgqSl5MfT1zcnR+dO2NIs8HBBI0l7vAO9v8kJ+lV33c01HMs8OwVRtM+oPEdyTbl4oRHCqSaUN78Ayl3EUkjyaVeuwRgtpwcqINOsqkyji1RMOeMheRTDo09eQOcN6Kxf+xhS0bZD+ByhCLfulWxOXxrkCcshYnA5wD2qfZ+GFFBQpge4sbOuwxrNiJO6WX/YFPBZg2+4KQygiYj7iJESxDQNrIbvfgJcL/Uwlg+rQXFrzKTrDQZIy1wb/YzI3Q24sI+dWyTy6jxrXXZnWgAwf6kJHFXMrm7h43m2R+iUYXwQLa+58CYReu97HV6Y7MDQqvcIFZ9c+wRHiuzoUjLFv4HqgNYPlnmWTlaUaH1symSg//f9aXUfMizrB8NbiqTdihThcXQTnjiaNYKcqwW5Y8jTxrRDPr+zINRGZRKeCBAbZxD6OLhCPTtHRGChCAMA3nldz4lTEGj8+ns/4wMuWqw+EEg1JCDPWpGFIF5oYASu0xVHqdX+VdnR3t5H2hA1aNbQzEe1Sn+Lad4hFWZPM7gMW/ByEt8aghlq5JLozmd5KHUN8FEVNzTPTV11+WHmlAlgSQ6II/Byw49+VwAQCMgZuH6gaXl1ERDYSeu78UtFvh3vSK156Cc3h8a1qdZF2gtO5NRqyf49yzIi3txc6bRK3H0BbwvaVFVF8Wbuoo6sIY5BJV9sgsdyTbhkfhBKLj/+adByj+IG5YfqgoeTVq+PPj/oNVvfK9aAcNDNKRBk0Kp5yguLW7seauPUkljXqKpThJj8Q+D0GrSqr/iEiXWdMPzYjuR1XhG6N1JwbhDxHFan80KYr13vSuG1x64EVchu4D6HTfb1H84s/W05PNfkUAzE9aaeDoVlbn57zOVVWxDNZCvOhIIi0cz9Jt5LJP2nvpMP3Wuw0C1jYEdt/s7TOhJQZpXHjjB3eoGKf8HDqIqqv+cDXx3ovhPwpp07dgezKK/F+0JGi5lRX4hXess0CaIX5nxYPnwryE/xbzYo/0vNwe1mEAjXdfWGvCktQ/BGuSvCcKrYcNkfcah4bx2M/9eLA2QqxNdCsSqe2lrE+omt1ggx1PFa9ne9b3gXzaA3oH0QIY85oCY6mMf1hfCmA1twfxZYBbHRo1o1E7qFDYc3tuWCGvnwqYN3ttrIH/Ld5dIOKe7nk4EpvibBIL1k0h4Cv+M9WBWIHLphKxIOaqf3Nq9MQG1VwMZy+DUqN94juqrqrQjxLMns0sdGF56aAggNpxREljQ4sEvyjR019wuQeWKJc9Raz+vqoNOQuN/Ok7JRZDBHj0Jx7Vqi+QJIfqymM/XTawl8IEkWL/hNvMZ+DWvoqg915azfX80uQFMei+KECxwr61abRsKEqrwJTl3cnYqtwpiBsOqqY9nTQQ9eo9YIHvhhgJE7xzuAvUOGJs2YqNoH9zvUE6AD+p1CYXaZG9kFKU6ldK7zRjMXlscR+lNLXhACop2eweQB6eNjvNx4ByN5409fKk+08Ls7pkBFRqNhYusZOMErRGj4+2CB7Yjx3
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
