---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane
spec:
  encryptedData:
    creds: AgAXuC1MY7+vlEJm90aqvcu1gaWQV4Tupopj3P3+gZ3URsuL0Gel5Uecxt818ifcaAkQNsUjpSS4xm4BryrdWzwBYy+sBGlzjPvCYYChSzla/h4UOCUp5KJdne9eO3mXWYihJCl7+39fpo0zajh5Yz1SPkdgV0RjGyeO5Z7FfN34f7TZ+V5AEGXgCrli2KtLVZsuJJ4n6kS0d2vzj8Nq69YrqnvzYmQ6Aug2pfYQlgl6zstBD9CY6nae/pTXgbEK0SqctsbdGgefbz8V+VbbtOTpNFMVhsf/CjwT3FZLFg6h3KivHeQBKTCF/yVsQm9hBEA5Ua0PwdYRgIKf6u/YKXVf+V6dxuivojZJu330hoLylxR782Sbu9Gi6FRi6lepB+e7c6kGHD23cP2ddvZLdEPpoMu+y2rlqf0prTCpGQwVhKwPkIkiuJP8pbZ1Nyv7wpdHCo8WXZG0UqLNLrVNsQPt/J1h+UdLkAWL2jqhNdzWfwmB00nAvhy5M/vRnEccs/tVfrEGy1WNx+EgpnoiF3zHMexe6dfcl21/a4ARttv65O0WA0XVF21cxRSQn0k9DlGly/4869y6rrDFkeZ1pfFU5kWnv416v2Z8m2hJDnGOoGpIvH6lTPRBBOBkEauw1o4ZnsAuewTUgzLmkw43fFFGoumPisqcmcaPJCzGBHKCsE+dJPAmpbgd037w5r4M+sea2IQbXM4kfzzC87y4CphfHAPHpfWUEraALbM8pQ55yyGTlryeKa4uc9OfGk3QKOghzM9+tC0BBVpcmWfjoE/gJF0Z+Hyo8oCqP7BvMcZWCu2sO8gsZjE7jClF8qFSo/ttzIMz+0E2odFyeUgmV0ICjWUPnVSnoNjk0TKswCtnhrYnkMwKAarM5Ym+8KqMdy8DS7smbrKSgQiozIcIdUhgcmQDjEDDhJKlGl2J3bslNaveY3GM266qK4291fLFrT7tFEFsne6kBWVEJSnuiLD7TvljegqqFNIpxz+G4P55M8GZlcD3xzJnhxRsJQ2Z5kJTGEl0KaCfAppqA+mwyGFeWpXtken95IY/p/E2xM83J3svSKN7q+ESwjaiAwtdc6PuXAr2xqMwvcukULhw5tu0t3tuHjr2hcKL3dmd6/Aq76FQ8/xc2MA8HDpGTTEpkFEBkXoWbXrGK5bzLZ0laChRns5s88d1dqhkrfocgyhrYTcNiDNfIZdS07Km+z2AWIFXzOXStSf+vMXLi5u7db/qwmumTbZRX1NpU8AHMSIFIaHwAaylxgdy82IpFD7BrxLTw2BVaOgYndtDIZVsFpOqplSQB81uRskHOJSlPlsUS7Yp123XbAj3ArPgCeZ9qaSZNfw7bJJqj+s+OZDxQ1/crcNIq9aWlWrXwQ2mRSMMYhpTMyRD3Wk8DFxj/xMVmPZcFJ5uFbDZQZ0RvEjWRl6OH4w5qejJo3JmIJKY674qFi1l8bkT7pl+m9hsrn40qurVctL3FM99mkd1wMPu2QbNfictujw8GbTF8EmTCeHNClvC9qJZijzb96XsmT0DGr0fQybA
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane
