---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCXutrIhN+ta0RkwgMT+ug3Vn/7IFvOjNvWZiHhw0suAHIVHGirMD34rzMwP+suz4Hr0JoKXz5iTrBj4d3KOJ1NnUQ2YPe+sRncQU5Wl/wuYWTKZi0mjwbx/KS+JwV+5yhdJfRLZh2kyp90vUnq61KVX0rpK+b219+9x/YRpxHMrPMdDi0t5uDQNv6CtrCgNGFKvpI1UiMaOhPuI7Z6bITo6LNhteNcTopX46WquDraOoa9aZTOp8J+sRG8d4SKdd6LRq/x7jRck5OEdxwglZp68O16OT7uTd2rBHB8OJzutMA2ug7FLBdnrUhJkOn1QygxBCPEdhp/jTscgQRlc2b4HcnuDkXVyl8JBiJ9yP92IxgYC5ES4hnaKnS17MevoRtxe7m98m6RH68pByNI7OZuRmnKw1m9usBYXgqChviOKrAdz1Ag7pIDroLIGQoAgu0A5QYxyIP2pRlkZnqhkg2Rc1TYcrRimC3r9i3cUr7u38RgH2DViCD11NqTInRqfWyPpPIPkMK0P54dCsE+qa6NS4ZVrsEYFIie2LKT9IMoDBziKRnK92y7auuRKRhDG2Dq3s8V/GlVMpLV/RaQ4lukmyyjv+QRpsKDkGm4xMSrMBY3EnXCkcbHERBpyR4JvdvzhBvHtakmV50DPQb+WEtm2CWeyPHzaGLliLxSfS3USALZdizg1R/7r5s+aAchrnTcyRyvn8z/+2J9ESkgVSvtTSapu4zXMlNGXwa4cxWz4gS88tJCbgoAO+l2OG0BE1a7gWrz8LwVmzeIDyPpYIIlu3IGZAFK7O7HPT9gw6PscTKU9z8zpGvEl1OQfsbEgVdGx3wwaYlR7tUkjJd6Cv42aKRfGZIPu7DROLbPyCXGwqI34rjLXl/oLaHnphlekRFKLSQH9KIa1/poPYetIBwoci2Bae7HV54VrdxuV+pzOlP1XjQOTEMbYcWI5u0pkGG5uAcsZf7qRGYu+c1kPDrCyrsbWpXBY++5ZgBC7OG33db0WYwZCXYRX1Nvolh1MXiLraabTCvEKIKhN8E9mAsCpADAsGfaPUxAixXmZ2qh8sZU7p72ZzBxqTCXf6wjutLHyoQK9UOdm5BviCXX2MitxYxZJxUyA0NI2Jjzu1GK6+XYVpqa0vYF+XQUU9tJ76Pht7H02m2qKVp08jzDcLGqzbN6PLTdcvL6e1cB3qQipbY/ge8BjJ7kRinu90AGWjxXWUh5Z+jNRbQfVYymRvvtkhluXQ6Pa76TveLxVhfzQgxw/5lh/TCivOraPVB6IBRI4d1RLFp9mV58ODAHLiwjDjj85GxxrJ21EGg7CSA02NYhcHQwcxYTiBsmN90XwsyvvCoNzIg48zIUAVJkgsonpeb9qG9piU1KrWNKpNPtm2MyH8Abs/cIpsL3d7j+rXe6dGmnxFpF0pne+SYCyDzeTgBDVx8zOin3Ezce69jHLuMBWaHinvZKVf2vjg/1P29B4qodFCjey5a0XvuVeeGWOpp0Zm3/dvLpFkv720mxQU0j1NxMM24N9ISYtuFqHzPJJDIS
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
