---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBIXxo//SvuMu6MgbWpTv3SJcHqpiDWKA/npkAKiaIICKPZdwiYbqzFG38GTOXJ2B4kilfarQ5FcNBU93aAXXaQxPi/1rBWVXszSAEAcOwnTvENmJYiUVMkT2FHMiPix+BrveHXSpQllTpxadGm2PXJ9CtUPcGVB4sEmYwd5UihH6ipjGqAH0yA88l6QrefYm9PshLXiFgm7aRfNHO95wXdm/HmnFNkSNeQDl4UkBqZk+aV61DXINDTFzATt384fyzwKPOeFnFu6of6Rl8rf5e9ja8/APRgtYXPEYHRNm0/472PKBGjSSSeTMfgYpZsBkj1QlSOd5U1Hbk4HXDdJC/MHAXnxI2HOPo+rNidWNZSDX+Lt/xSnMs9cwjiPuBYGVWEQcVYzUr1tsPfetu0Uxk6gOyQkdfe4fYn+uS05gM82XUTpqV+yKOMPTCOJ5qJUCscVaRoOl9z1HUxmqBBaZI/RvL1e+0aCNdqdG6b9Wpl+OGBYljcJ8iCdqKItAuWIUbX4Nta+qntA/4qG6onC2tU5nOv1mjtC3R6mvjfqF3Ec0owrRNUcWsJz8RNLu+yoa08WjIFzeXerUad+s371oA7IcV8RJ3XfkOR50yJycKwOlN/2fbMZgbsBh1UtE7U2kq/o1wkJiR5ebLDcsTrLh9tP6VTquTsCSIpjDs73tCkE19ys3rD4s3zD4JolS7xtESBV5MLy5ASkb9zS+E98Fmb9NqxNDJuJfHUTKrhdiqGRcfXuSyzL7ZLBpaGAO4Z+ZcpbrhREtWwj1az2kEd+/ltGLjQNreffXTa26ZF2Eio9rYfrhu47UzvLJYCS0ImqzBYHBrFpxGl6Y5UZe4ssuIQE4iDSNEyIFg0aCvNA0MUo26e4RDSaZq1IkDV7B+WUVyUhUHaHKgh9DSeQ/qrsPvaq/BjHVe5wzHaixL99CyPVXvcwwAHjP9bohH9ts09mkiAufAlQ0aMaBkmPRuK6pM7HiEuH1Viqkkgdk48cxlofyZN2pYhOR2cqoIOx8ZW5GPaByM3Puc/SFSPsgvmS47NLKfKlBkCgCCFX2ipWTnx7FyEhi9qEgGSrUpQC+/TXpeWFur4QQwDWzWxiV9UpKyGc9OsreJZ9S1sVWKihc3UUnwUf4UmhKpGs0YFIqH30KebKGt/edqJ4IOTkrU9RrdqKbvOWJOSXGrXj7luKw0Gza6vFWwPzr2AqSfVRGNTMZMYllsIlIoUa4AGlX86/f8tqdLdMnoGzTJvcE3Rnp92Mj0nAWH6scFpssiuzQaRrfoVm6QpXCzVgRfH23Q8xdKXEn7zOI4XSGCC17biP3hFAMQaiZsEUmsMgRwa5RB5EcNPVuUz6GFuzTZ3dAtaJOOrmqjxLyryMZJ//dc6jqhWRiwspMM/gYO1ZNjhlipqyaGc1UBQ24uHaMtyU8x4RjI9QGpWGGVuqhbvuHQXnEOmnUgT3FGr/sJBNeRq4adPU80icAsROFZYVR4YLClGIDpmhD6DNizeNPvXFGwKM0M2vW1b6QFHbhKTuNC1aogHiLbeNSel
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
