---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAD7yBp3I2TBzMpSP/Hp58q8CZmf0ar8bLOT+cagaq+PGmOp7I6y/v5k0YSDkMj6/BClngrYhQQW6dqxBCMQuYnyluLD6Q7e7HNOHiAXrWffS1x9ujD8uZP3DFmyndihsbFrk5cWxlaZjQK0FaHRzW7SgjoCsb0Yg22Ec1X9EUP5mu2R/3SE924BzlQ75aeCImoxg58gAQxdU0hdpn2KsQ3o2J6yZE2iYOEpCcexybj/FAZT0tsTLWYLQcHEmmLZN/Rn/AloM5wT5NZL3uvfktUZ0CulquiWi7hEXBVqhKQh4ZWnBUWxv73fC8bAEitsogks4S3vAtHGVMtAnpLGghMFY9m8HadfBb6Sgja/4ilYsE9sXWU4Hbe2ENTL1MMOoVv6q+0NlDLfMM9syPHu0yqhcBRuu5+zpts9eQYTv1DQ+nc0eADzILUofx3OuW+sSPnXbz6MiSj2eRILZklDALHWY4dNsXSonsD99/GF/+jCw5zMfLUcDpDeyqCdjGWsRWtbYnNjbE/fixGr0xEt4FonzU+u49iExy5Spqe8Nm/hASJN5Wza9qqjHs2KN/V67PG9sX+3dzZSfjlyxANgSaSyqm8DI+QlJc6it/CSiPNSnm+T26YpPKQC5cozIETdNbhxcyDThat0dJ7sGhYw9JNR4ESOyHV2sHMklptzHfCXiLPF/7PWC7J4mAGwxhjRaubsta0cKDbpFCYxfagiD23pbROtKTDGLwcaf9VSV6b9bZgpaqWiEHL7AB5CJSxyR3goZK7tyWDDd2MLXwxPDHtZaXmKD70onGJ3Nss7gOmUUINzrscLoY+m1Qdl/pwXac0Y3s7DGzfSfTwsQQGrdA0S9UfkWd+oHqtyqDxKInx9Rr/Ge2QfmLvfK5ZiwaTCR0prdyZsY1zy/jDFXtBhSwGenxyRMHuQ8ZGmAYUyYRJMW8KQ3uEuWg0SFUOWGzxTShJyjxomug/q36eC/lBn1can2eo9KGVxNzuhtiDtp+tiGP0QzYJUTTZ/UNU957hWJbsq8UEQH68L1X7VOSHQr7uCWu/fdsUyqf8QSPgpa5sZKsx8ufOLU3+w0++lxymhx4Zqf//y4zxoMHheOqS++va5BQZVnXIMMW6qYbiiDaMb/2pcNi/wFXnjNI/Re/SSiSCK6MdHlKQfhs96gHdAnzNPlPGm4YxL/uKw6dCzd3S0HXXTWrA8a26w/MFUjS0fX4q6kSA3tMHdIje7le7QSimEz0oNyqZVh+/ckvI24+gfxakb/i0XKAZ+3ctEHcqKkwEoHrDY3PvBXRGA3CGn9pc3J6KBFKFJMDjmkA+tiKn8umIucDYNhXOhQL/XfmoQEgFbzvKZ8k7oSPr4nEBDP+rwrVJhESzUHjT6DrUCsOIHklR2kfW5yD+n1TqAp5QyaDCeTR85CeEQkfFCEgOC+nXJlx8RtHJ0PrayjAWsLuS91tIBGlTMg14WIc6a6p6gTOFFhz1b+aGlkYQ75aVf98kQXjyP0n4VbO0sGm0F+O7qWM0eJsW3xUuj5RzNNp5pk4TSPJ0
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
