---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCIoO493iImAZnHmPMp/Kx4er5csvHU20grZjwYlU7RT3h+1zeIRefK+/Wy0OhtDl+WpDX1A93JgBScPibXr90qGDWwoYT6BNZdUBrdxJFxGJLVjCfosdkC3RYHiS8RITBWLSqULeBca7fmGCC8aJ6MLY0002QdvuEi3GGieefmN0JSjYvL52BIjKPTRMhFjUxBId/et3Q5dLKYSFCvjqGGLYgk8KcfGgIE2GW8/PKYrkfBatz5ROg4klDwPylioCUcHBt2StbGZkwjb3Vz8twB4/qQhTLtOcydW98mUjb9EMDYvuGZsSMOG9UrE6Tsq3iQAC1Jv4Z3MDGC8pVgKYbla40nywYpGyKmhmEOy7w5VSJjLnyW5xW6946YWdJ3OaUVmBHYz+mIaYEQ0fY8oh5/DrBQPm+0Fw7Hlw7AALF7WiUNRutD+JCAPtVTOKmBub/SXakH9PuZrOz8wYPebSLx81CPeJgEKw80iC67xCD0wuCagfoyjZrxGj4c995jI7YXCZdx6ieN4DN/A1w2IpbG+OZ85UKIkgq2Enj3qx6x0OHhRAug5uRc9bqlur5f4kwUo7fgHBBWLZLIonzwuZnqoVCqg9gaRkDXRj8cmDJ1tuR3FM2oMU1R+QWIBsQ1RUysrWvLbTh+fWqt+sahRjP3DfRgqtBBIfgAh8YdUrlY5u5ZNXG8/yRJV8CzQgf6evLFOINewLCSO2Dq36sCVlr16TLlKI0G+cHZy1XZFqVRlvsRIeSrFzzwj4ZofmJ7USRmfcrOjHbiROwbp+OH14bKiFnNbEGG1J3lXUQUEglH5js9RI0zIaV8e76wCJtB0tJOgl8bdVxoI+/D0q8WOZpge1F2bwSTe/Gdqw+FkLVa/bLBIxcL17cr/aUaIN/nIhAnKjtY0f8LluTPc1jDtZ29p+mI9QxGXtORurdb9pzqYGfDLVPqX3SLB6VCdHgDi0txg+iuVgxMvQax+6+EI+u3TSAtEfEUopeBbeupeUT2uiXQc0x1K7mfD2n5T1h6IEuuCK7Azk/o/PP8ws4LCrVx+QrNUQE9LUZuRMl0cIVX6GABmvXMHh3MgpGuWVtVoNge0VrGumB0/3vux+SJIUAd2aIjEbY3w8+TKoZ7JiouKjCq6JKdUw8+BI+xSGb4JPSim4ettawxmKTCMTppELpWeVwchLvIG9xteu4mWMjwq+RmfzwVEN1ut/KHBprD5BCuwBIaObEC4IHMiIQiWoy3S+bA7qFckm4Ay3cR1KS3wSD6aOJNYvllIQuWj/ZNjXOPsxwLKNx79eGQymAQGPEHy1jnf6kF8cTB1ozwi98PmLZp8DcIm41Iw3hCjS0HLtHk2aC39akISh5bMBxsJYLYoklNxN0KfH3Wpqyq5VWKt5n2hzoNALVCqwjgkFelschbe/B8+rgGQ+2wslmRZqHNZkt8EPyuVAEtqTOHiTgT8INVLwSLyw0NU4GylxCmiWtWvc5SH6L0tv0h+t4BhYxdFqgGWKSwVNpt2196k1ucgaGImmkzw1exJ3g6LFaoR1avLgYJ
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
