---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCofU2J0u7b8Vr5EHxKKQn0Vl4sVXxenLDhjN99ePAl+OYQEdH/n7heMrHFo3q0OQWgXWH1Wfbx4MeEholgBqiyUGc805gw60mIJ4l1vAPptlQKPIEEcIIGCVhdTPZemKpFxVubgh8YXfOWa4jwWPt1XYtxXHMubvHJMtTw06gYbBaSUtx++Gv8sDrwnrG7o4B/nejC5UNTofLUIesGVGFN41uJSLelBD+ZocXrzUPf2Kct6lagNcIsS0CpWO/jhGW7eMeh7S/drACH/H4pSWTEQKRIt19+SQpoWXWbvGrNepM37hwrbqCvuO4SY4mW+HzmUSi8oTE1FhwFScY78MZR6uhLIoWK22oIGDlQFgpQY3/LvpfaOhPMyQwzNtRlAHx8V2T9Da6H/HTgzDRI1FvSAk4jdIbR5Rie0vueA/ykD+zqLgE3Mh6EMzJGNq+g7v061XmvgsV5NLKp+F2n+wFSRwEy794yuIcc0hP43mSgC0yENk/pvFv544BoMtRuiGqqSG22seXF+/DRrKeog/1qKQ1e3e8gX2w5O20ydUKX5yzF3G7pnohjwMmWia5W4tGF0iXHHnrEd24CsKCXHwwQkScNTcMkF7whcMPPFUMGbTeOMfZvnS/XshaylLqQp01+akra3wD5bPM724OSKZzBvzFgMnkTtit4F2WBwtFRnypaq/Wd/pvYqFJW261B2Wwe9L/xEq9+OqmCQ+JB1Bd7YYve+8rhJk1VSXnK30w4GOM/Zk8rY3Rb3A3hKq171lEvh5DVmTaMh69ZKOqPYwqN9xPJM10aVl12gP61X1K8ia80nkXFC8y8n0BvtjueE5du6VwtTkDAS1VTaxsxX44BO6xB/8kGaD1896XUBK1P9qCRt7WMN8jXoMp203Thgau+til+uri3tgiZbM2i8qhJhYhfCUREt4pROHvzDMOkspT6XnUamSEfu8FnU4B6Hl5sAWIyQSBTq5qxHhjK80rU18kOG4LM592HgpRIxe9/uDqj+ET1jcmw8E15+wzeXHW3QziXpbzC8mzyb9vbKFqOruXzyTJf3f7BUncmfrgFr7e9LSSw9qlM/6bdYVprT9UfX5XDqg0GX4htCpp8pziWjrrRyJIPbF1WdDQAV9gPdLGHsZHnws34JwPBZVNiKDISgMDlNJSs8uXP+RKSHWOFfSM1shsNmFNN1/WHsNoIKeH4ENLnZwxp4t1Xy5RW+xCZeGIjHCJLcuIBE4uU4wuZCZ8UU1Fh8tz54pIVEicwDXHV6ivnn3c8GIq7HVoJFZjqIc1eNYJORkU5ojxUryzD0XJEFyiB6qgVxl/ddNqX+tK+Pd2IlUKuZPmg5I3BYEGq78Cs+gdk9zjI5D8tj+X4ZhppmTerSk+AusVC4v5PEq8AlMlRfC+LZRNZO4vGfQx5Q+4x0DqndLfPj6aCNEybioN10B9dYuFvb8BqzZu1nftDncqVhEL2lwWUgbuGcY5n/LmqG1Ed0kwgpWtJlOg7aokigSoHW75SjgBnhqKtrSFODxbpT8S9dCDGAx2dx1J5mN32
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
