apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-route
spec:
  parentRefs:
    - name: pod-gateway
      sectionName: https-listener
      kind: Gateway
      namespace: projectcontour
  hostnames:
    - "tekton.pod.nvtc.io"
  rules:
    - backendRefs:
        - name: tekton-dashboard
          port: 9097
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-http-redirect-route
spec:
  parentRefs:
    - name: pod-gateway
      sectionName: http-listener
      kind: Gateway
      namespace: projectcontour
  hostnames:
    - "tekton.pod.nvtc.io"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
